services:
  - type: cron
    name: mlb-auto-blog-writer-gpt
    env: python
    schedule: "0 11 * * *"  # Run daily at 11 AM UTC (6 AM ET)
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
